name: Update GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "app/**"

jobs:
  run-conditional-job:
    if: github.actor == 'WebDesignerCameron'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
        shell: bash

      - name: Setup and Cleanup
        run: |
          rm -rf dist .output docs/**
        shell: bash

      - name: Generate and Move
        run: |
          npx nuxt generate
          mv .output/public/** ./docs/
        shell: bash

      - name: Commit and Push
        run: |
          git add .
          git commit -m "gh-pages: update" || echo "No changes to commit"
          git push origin main
        shell: bash
